{% set name = "python-gmatelastic" %}
{% set version = "0.2.0" %}
{% set sha256 = "f3f3dae9e24392da489e0ac10f59a002507a06a3a5bacdd493c887a8f30a3fcb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastic/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
    - gmattensor
  run:
    - python

test:
  imports:
    - GMatElastic

about:
  home: https://github.com/tdegeus/GMatElastic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Linear elastic material model (Python wrapper).
  description: Linear elastic material model (Python wrapper).
  doc_url: https://github.com/tdegeus/GMatElastic
  dev_url: https://github.com/tdegeus/GMatElastic

extra:
  recipe-maintainers:
    - tdegeus
