{% set name = "python-gmatelastic" %}
{% set version = "0.1.0" %}
{% set sha256 = "962aad87e9738a8734c99d7f57ef952767710e679445e06dd85af44553ab07d6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastic/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
  run:
    - python

test:
  imports:
    - GMatElastic

about:
  home: https://github.com/tdegeus/GMatElastic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Linear elastic material model (Python wrapper).'
  description: 'Linear elastic material model (Python wrapper).'
  doc_url: https://github.com/tdegeus/GMatElastic
  dev_url: https://github.com/tdegeus/GMatElastic

extra:
  recipe-maintainers:
    - tdegeus
